name: Deploy App to New VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: yarn install

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          command_timeout: 3600s
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            cd ${{ secrets.DEPLOY_PATH }} || mkdir -p ${{ secrets.DEPLOY_PATH }}

            git pull origin main || git clone https://github.com/shafayeatt1995/plexus_frontend ${{ secrets.DEPLOY_PATH }}

            cd ${{ secrets.DEPLOY_PATH }}

            cat > .env <<EOF
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}
            NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }}
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            EOF

            yarn install --frozen-lockfile
            NODE_OPTIONS="--max-old-space-size=3072" yarn build

            pm2 describe app_3001 &>/dev/null && pm2 restart app_3001 || pm2 start yarn --name app_3001 -- start

            pm2 save
            sudo nginx -t
            sudo systemctl reload nginx
